name: Build Firefox OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip python2

    - name: Clone B2G repo
      run: |
        mkdir ~/firefoxos
        cd ~/firefoxos
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH
    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        repo init -u https://github.com/mozilla-b2g/B2G.git -b master
        working-directory: firefoxos

    - name: Repo Sync
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
        working-directory: firefoxos
    - name: Clone dt
      run: |
        git clone https://github.com/Vin4ester33/android-device-zte-Blade_A510.git vendor/zte/Blade_A510
        git clone https://github.com/Vin4ester33/android-device-zte-Blade_A510.git device/zte/Blade_A510
        working-directory: firefoxos

    - name: Build Firefox OS
      run: |
        cd ~/firefoxos
        ./config.sh flame
        ./build.sh